# Site settings
title: DO NOT PANIC
description: "Everything is going to be okay"
url: "https://surviv.hyl.uk"
author:
  name: "Benny & Willy"
  email: "b@hyl.uk"
  url: "https://hyl.uk"

# Build settings
baseurl:
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  recipes:
    output: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
