version: "3"

services:
  site:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --livereload --verbose --host 0.0.0.0
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
